<a href="https://colab.research.google.com/github/RAVIKUMARBALIJA/huggingface_transformers/blob/main/1_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install transformers

     |████████████████████████████████| 2.3MB 6.8MB/s 
     |████████████████████████████████| 901kB 36.1MB/s 
     |████████████████████████████████| 3.3MB 50.0MB/s 


In [3]:
from transformers import pipeline

In [4]:
classifier=pipeline('sentiment-analysis')

In [5]:
classifier("I am happy to be learning about transformers")

[{'label': 'POSITIVE', 'score': 0.999858558177948}]

In [6]:
classifier('I am not happy')

[{'label': 'NEGATIVE', 'score': 0.9997896552085876}]

In [7]:
classifier(['I am some how happier','pizza is not that good but crust is good'])

[{'label': 'POSITIVE', 'score': 0.9973820447921753},
 {'label': 'POSITIVE', 'score': 0.9985012412071228}]

In [8]:
results=classifier(["We hope you don't hate it","pizza is not that good but crust is good"])

In [9]:
for item in results:
  print(f"label : {item['label']}, with score {item['score']}")

label : POSITIVE, with score 0.8319633603096008
label : POSITIVE, with score 0.9985012412071228


In [10]:
multilingual_classifier=pipeline('sentiment-analysis',model='nlptown/bert-base-multilingual-uncased-sentiment')

In [11]:
multilingual_classifier('i am happy')

[{'label': '5 stars', 'score': 0.5958592295646667}]

In [12]:
multilingual_classifier('i am angry')

[{'label': '1 star', 'score': 0.5581967234611511}]

In [13]:
multilingual_classifier("Esperamos que no lo odie.")

[{'label': '3 stars', 'score': 0.33688196539878845}]

In [14]:
from transformers import AutoTokenizer,TFAutoModelForSequenceClassification

In [15]:
model_name='nlptown/bert-base-multilingual-uncased-sentiment'
model=TFAutoModelForSequenceClassification.from_pretrained(model_name,from_pt=True)
tokenizer=AutoTokenizer.from_pretrained(model_name)
classifier=pipeline('sentiment-analysis',model=model,tokenizer=tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [16]:
classifier('I am happy')

[{'label': '5 stars', 'score': 0.5958592295646667}]

In [17]:
from transformers import AutoTokenizer,TFAutoModelForSequenceClassification
model_name='distilbert-base-uncased-finetuned-sst-2-english'
tf_model=TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer=AutoTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_57']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
inputs=tokenizer("We are very happy to show you the 🤗 Transformers library.")

In [19]:
print(inputs)

{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [20]:
tf_batch=tokenizer(
    text=["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors='tf'
)

In [21]:
print(tf_batch)

{'input_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996,
          100, 19081,  3075,  1012,   102],
       [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,
         1012,   102,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}


In [22]:
for key,value in tf_batch.items():
  print(f"key : {key}")
  print(f"value : {value}")

key : input_ids
value : [[  101  2057  2024  2200  3407  2000  2265  2017  1996   100 19081  3075
   1012   102]
 [  101  2057  3246  2017  2123  1005  1056  5223  2009  1012   102     0
      0     0]]
key : attention_mask
value : [[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0]]


In [24]:
tf_output=tf_model(tf_batch)

In [25]:
tf_output

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
                             array([[-4.0832963 ,  4.336415  ],
                                    [ 0.08180901, -0.04178483]], dtype=float32)>)])

In [27]:
tf_output[0]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.0832963 ,  4.336415  ],
       [ 0.08180901, -0.04178483]], dtype=float32)>

In [26]:
import tensorflow as tf

In [30]:
tf_predictions=tf.nn.softmax(tf_output[0],axis=-1)

In [31]:
tf_predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.2042972e-04, 9.9977952e-01],
       [5.3085917e-01, 4.6914080e-01]], dtype=float32)>

In [33]:
tf_outputs=tf_model(tf_batch,labels=tf.constant([0,1]))

In [34]:
tf_outputs

TFSequenceClassifierOutput([('loss',
                             <tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.419931 , 0.7568524], dtype=float32)>),
                            ('logits',
                             <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
                             array([[-4.0832963 ,  4.336415  ],
                                    [ 0.08180901, -0.04178483]], dtype=float32)>)])