In [98]:
import tensorflow as tf

In [99]:
from transformers import pipeline,TFAutoModel,AutoTokenizer,TFAutoModelForSequenceClassification

### Pipeline


In [100]:
Sentiment_cls=pipeline('sentiment-analysis')
Sentiment_cls(["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"])

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_234']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


[{'label': 'POSITIVE', 'score': 0.9598045945167542},
 {'label': 'NEGATIVE', 'score': 0.9994558095932007}]

### Using TOkenizer and TFAutomodel and TfAutoModelforSequenceClassifications

In [101]:
checkpoint='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer=AutoTokenizer.from_pretrained(checkpoint)

In [102]:
sents=["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]

In [103]:
tokens=tokenizer(sents,padding=True,truncation=True,return_tensors='tf')

In [104]:
tokens.input_ids

<tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,
            0,     0,     0,     0,     0,     0,     0]])>

In [105]:
tokens.attention_mask

<tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [106]:
#checkpoint='distilbert-base-uncased-finetuned-sst-2-english'
classifier=TFAutoModel.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertModel: ['dropout_19', 'classifier', 'pre_classifier']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [107]:
outputs=classifier(tokens)

In [108]:
outputs

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(2, 16, 768), dtype=float32, numpy=
array([[[-0.17978038,  0.23332836,  0.6320989 , ..., -0.3016661 ,
          0.5008197 ,  0.14814377],
        [ 0.27577674,  0.6497122 ,  0.3199774 , ..., -0.07599581,
          0.51361704,  0.13292293],
        [ 0.90458477,  0.09851376,  0.29497236, ...,  0.33519462,
         -0.1407414 , -0.6464027 ],
        ...,
        [ 0.1465894 ,  0.5660601 ,  0.32352865, ..., -0.33757478,
          0.5099775 , -0.05610837],
        [ 0.750004  ,  0.04872627,  0.1737999 , ...,  0.46841493,
          0.00296694, -0.60837525],
        [ 0.05194384,  0.37294826,  0.5223329 , ...,  0.35840508,
          0.6500423 , -0.38829738]],

       [[-0.29370657,  0.72825617, -0.14972645, ..., -0.11868118,
         -1.0226724 , -0.04215667],
        [-0.2206362 ,  0.93838465, -0.0951251 , ..., -0.36431676,
         -0.66052175,  0.2406969 ],
        [-0.1536077 ,  0.89875007, -0.07276424, ..., -0.21891779,
         -0.8

In [109]:
outputs.last_hidden_state.shape

TensorShape([2, 16, 768])

### TFAutoModelforSequenceClassification

In [110]:
#checkpoint='distilbert-base-uncased-finetuned-sst-2-english'
sent_cls=TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_273']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [111]:
outputs=sent_cls(tokens)

In [112]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5606962,  1.6122811],
       [ 4.1692314, -3.3464477]], dtype=float32)>, hidden_states=None, attentions=None)

In [113]:
outputs.logits.shape

TensorShape([2, 2])

In [114]:
outputs.logits

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5606962,  1.6122811],
       [ 4.1692314, -3.3464477]], dtype=float32)>

In [115]:
predictions=tf.math.softmax(outputs.logits,axis=-1)

In [116]:
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.0195394e-02, 9.5980465e-01],
       [9.9945587e-01, 5.4418371e-04]], dtype=float32)>

In [117]:
tf.argmax(predictions,axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0], dtype=int64)>

In [118]:
sent_cls.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [119]:
sents

["I've been waiting for a HuggingFace course my whole life.",
 'I hate this so much!']

In [120]:
4.0195394e-02>9.5980465e-01

False