In [14]:
import tensorflow as tf

In [2]:
from transformers import pipeline
from transformers import AutoTokenizer,TFAutoModel,TFAutoModelForSequenceClassification
from transformers import AutoConfig,BertConfig,GPT2Config
from transformers import TFBertModel,TFGPT2Model

In [8]:
from transformers import BertTokenizer

In [5]:
##Loading model from pretrained weights # from model checkpoint
bert_model=TFBertModel.from_pretrained('bert-base-cased')

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [6]:
#saving the model to a directory
bert_model.save_pretrained('bert_model_to_save')

In [7]:
bert_model.summary()

Model: "tf_bert_model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  108310272 
Total params: 108,310,272
Trainable params: 108,310,272
Non-trainable params: 0
_________________________________________________________________


In [9]:
sents=['Hello. how are you','Good Morning']

In [11]:
bert_tokenizers=BertTokenizer.from_pretrained('bert-base-cased')

Downloading: 100%|██████████| 213k/213k [00:00<00:00, 605kB/s]
Downloading: 100%|██████████| 29.0/29.0 [00:00<00:00, 14.5kB/s]
Downloading: 100%|██████████| 436k/436k [00:00<00:00, 944kB/s]


In [31]:
tokens=bert_tokenizers(sents,padding=True,truncation=True,return_tensors='tf')

In [32]:
tokens

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[ 101, 8667,  119, 1293, 1132, 1128,  102],
       [ 101, 2750, 7151,  102,    0,    0,    0]])>, 'token_type_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0]])>}

In [27]:
#outputs_tensors=tf.constant(outputs)

In [23]:
bert_model=TFBertModel.from_pretrained('bert-base-cased')

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [33]:
outputs=bert_model(tokens)


In [36]:
outputs.last_hidden_state.shape

TensorShape([2, 7, 768])