In [43]:
import tensorflow as tf
from transformers import AutoTokenizer,TFAutoModelForSequenceClassification
import numpy as np

In [44]:
checkpoint='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer=AutoTokenizer.from_pretrained(checkpoint)

In [45]:
sents=["I've been waiting for a HuggingFace course my whole life.","I hate this so much"]

In [46]:
"""
tokens=tokenizer.tokenize(sents)
input_ids=tokenizer.convert_tokens_to_ids(tokens)
final_input=tokenizer.prepare_for_model(input_ids,return_tensors='tf')
"""

"\ntokens=tokenizer.tokenize(sents)\ninput_ids=tokenizer.convert_tokens_to_ids(tokens)\nfinal_input=tokenizer.prepare_for_model(input_ids,return_tensors='tf')\n"

In [47]:
tokens=[tokenizer.tokenize(sent) for sent in sents]

In [48]:
tokens

[['i',
  "'",
  've',
  'been',
  'waiting',
  'for',
  'a',
  'hugging',
  '##face',
  'course',
  'my',
  'whole',
  'life',
  '.'],
 ['i', 'hate', 'this', 'so', 'much']]

In [49]:
input_ids=[tokenizer.convert_tokens_to_ids(token) for token in tokens]

In [50]:
input_ids

[[1045,
  1005,
  2310,
  2042,
  3403,
  2005,
  1037,
  17662,
  12172,
  2607,
  2026,
  2878,
  2166,
  1012],
 [1045, 5223, 2023, 2061, 2172]]

In [51]:
[tokenizer.decode(input_id) for input_id in input_ids]

["i've been waiting for a huggingface course my whole life.",
 'i hate this so much']

In [52]:
max_input_length=0
for input_id in input_ids:
    if len(input_id)>max_input_length:
        max_input_length=len(input_id)
for idx,input_id in enumerate(input_ids):
    if len(input_id)<max_input_length:
        pad_length=max_input_length-len(input_id)
        input_ids[idx]+=list(np.full((1,pad_length),tokenizer.pad_token_id,dtype=int).ravel())


In [ ]:
np.full((1,4),tokenizer.pad_token_id)

In [ ]:
tokenizer.pad_token_id

In [53]:
print(input_ids)

[[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012], [1045, 5223, 2023, 2061, 2172, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [54]:
attention_mask1=np.ones((1,14),dtype=np.int64)
attention_mask2=np.hstack([np.ones((1,7),dtype=np.int64),np.zeros((1,7),dtype=np.int64)])
attention_mask=np.vstack([attention_mask1,attention_mask2])
print(attention_mask)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 0 0 0 0 0 0]]


In [ ]:
attention_mask1=tf.constant(tf.ones((1,14),dtype=tf.int64))
attention_mask2=tf.concat([tf.ones((1,7),dtype=tf.int64),tf.zeros((1,7),dtype=tf.int64)],axis=1)
attention_mask=tf.concat([attention_mask1,attention_mask2],axis=0)
print(attention_mask)

In [55]:
final_input=[tokenizer.prepare_for_model(input_id,return_tensors='tf',attention_mask=attention_mask) for input_id in input_ids]

In [56]:
final_input

[{'input_ids': <tf.Tensor: shape=(16,), dtype=int32, numpy=
 array([  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102])>, 'attention_mask': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>},
 {'input_ids': <tf.Tensor: shape=(16,), dtype=int32, numpy=
 array([ 101, 1045, 5223, 2023, 2061, 2172,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  102])>, 'attention_mask': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>}]

In [ ]:
final_input=tf.convert_to_tensor(final_input)

In [ ]:
final_input

In [57]:
model=TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [58]:
model(tf.constant(input_ids[0]))

InvalidArgumentError: Input to reshape is a tensor with 14 values, but the requested shape has 196 [Op:Reshape]

In [ ]:
model(final_input)

In [ ]:
tokens=tokenizer(sents,padding=True,truncation=True,return_tensors='tf')
output_logits=model(tokens).logits

In [ ]:
output_logits

In [ ]:
a=[0,9,4,5]

In [ ]:
b=list(np.zeros((1,5),dtype=int).ravel())

In [ ]:
b

In [ ]:
a+b